name: florida-project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update .env file
        run: |
          content=$(cat ./src/.env.template)
          content="${content//\{PROJECT_TOKEN\}/${PROJECT_TOKEN}}"
          content="${content//\{APP_ID\}/${APP_ID}}"
          content="${content//\{APP_SECRET\}/${APP_SECRET}}"
          echo "$content" > ./src/.env

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/
          file: ./src/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/florida:${{ github.sha }}
